# Introduction to Scikit-Learn (sklearn)

This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover:

0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problems
3. Fit the model algorithm and use it for the problems
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting all together!

## 0. An End-to-End scikit-learn workflow

In [1]:
# Get the data ready
import pandas as pd
heart_disease = pd.read_csv("../data/raw/heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# let us  create the features matrix and the labels
#Create x (feature matrix)
x= heart_disease.drop("target",axis=1)

#Create y (labels)
y= heart_disease["target"]

In [3]:
#2 choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
# we'll keep the default hyper parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [5]:
clf.fit(x_train,y_train);

In [6]:
# make a pred
y_preds = clf.predict(x_test)
y_preds

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [7]:
y_test

22     1
40     1
232    0
230    0
45     1
      ..
203    0
111    1
128    1
171    0
294    0
Name: target, Length: 61, dtype: int64

In [8]:
# 4, evaluate the model this must be 1 because we are scoring the model with the test data
clf.score(x_train,y_train)

1.0

In [9]:
clf.score(x_test,y_test)

0.7704918032786885

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score;
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.71      0.65      0.68        23
           1       0.80      0.84      0.82        38

    accuracy                           0.77        61
   macro avg       0.76      0.75      0.75        61
weighted avg       0.77      0.77      0.77        61

In [11]:
confusion_matrix(y_test,y_preds)

array([[15,  8],
       [ 6, 32]])

In [12]:
accuracy_score(y_test,y_preds)

0.7704918032786885

In [13]:
# 5, improve a a model
# let us try different amount of n_estimators (which is one of the parameters of the model)

import numpy as np
np.random.seed(42)
for i in range (10,100,10):
    print(f"Trying model with {i} estimators ...")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print (f"Model accuracy test on  test set: {clf.score(x_test,y_test)*100:.2f}%")

Trying model with 10 estimators ...
Model accuracy test on  test set: 81.97%
Trying model with 20 estimators ...
Model accuracy test on  test set: 73.77%
Trying model with 30 estimators ...
Model accuracy test on  test set: 78.69%
Trying model with 40 estimators ...
Model accuracy test on  test set: 77.05%
Trying model with 50 estimators ...
Model accuracy test on  test set: 75.41%
Trying model with 60 estimators ...
Model accuracy test on  test set: 80.33%
Trying model with 70 estimators ...
Model accuracy test on  test set: 77.05%
Trying model with 80 estimators ...
Model accuracy test on  test set: 78.69%
Trying model with 90 estimators ...
Model accuracy test on  test set: 77.05%

In [14]:
# 6, save a model and load it 
import pickle

pickle.dump(clf,open("random_forest_model_1.pkl","wb")) #wb stands for write binary

In [15]:
loaded_model =pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(x_test,y_test)

0.7704918032786885

## 1. Getting our data ready to be used with machine learning
Three main things we have to do:

    1. Split the data into features and labels (Usually `x` and `y`)
    2. fill missing data (also called imputing) or disregard missing values
    3. converting non-numerical values to numerical values (also called feature encoding)

In [16]:
 heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [17]:
#Feature Matrix
X = heart_disease.drop("target", axis = 1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [18]:
#labels
Y = heart_disease.target
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [28]:
#split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

In [29]:
X_train.shape,  X_test.shape, Y_train.shape, Y_test.shape

((242, 13), (61, 13), (242,), (61,))