## 0. An End-to-End scikit-learn workflow

In [1]:
# Get the data ready
import pandas as pd
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# let us  create the features matrix and the labels
x= heart_disease.drop("target",axis=1)

#Create y (labels)
y= heart_disease["target"]

In [3]:
#2 choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
# we'll keep the default hyper parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [27]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [5]:
clf.fit(x_train,y_train);

In [6]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3
241,59,0,0,174,249,0,1,143,1,0.0,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,47,1,0,112,204,0,1,143,0,0.1,2,0,2
118,46,0,1,105,204,0,1,172,0,0.0,2,0,2
200,44,1,0,110,197,0,0,177,0,0.0,2,1,2
154,39,0,2,138,220,0,1,152,0,0.0,1,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2

In [7]:
# make a pred
y_preds = clf.predict(x_test)
y_preds

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1])

In [8]:
y_test

28     1
96     1
213    0
260    0
241    0
      ..
126    1
118    1
200    0
154    1
2      1
Name: target, Length: 61, dtype: int64

In [9]:
# evaluate the model this must be 1 because we are scoring the model with the test data
clf.score(x_train,y_train)

1.0

In [10]:
clf.score(x_test,y_test)

0.8688524590163934

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score;
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        23
           1       0.92      0.87      0.89        38

    accuracy                           0.87        61
   macro avg       0.86      0.87      0.86        61
weighted avg       0.87      0.87      0.87        61

In [12]:
confusion_matrix(y_test,y_preds)

array([[20,  3],
       [ 5, 33]])

In [13]:
accuracy_score(y_test,y_preds)

0.8688524590163934

In [14]:
# 5, improve a a model
# let us try different amount of n_estimators (which is one of the parameters of the model)

import numpy as np
np.random.seed(42)
for i in range (10,100,10):
    print(f"Trying model with {i} estimators ...")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print (f"Model accuracy test on  test set: {clf.score(x_test,y_test)*100:.2f}%")

Trying model with 10 estimators ...
Model accuracy test on  test set: 78.69%
Trying model with 20 estimators ...
Model accuracy test on  test set: 80.33%
Trying model with 30 estimators ...
Model accuracy test on  test set: 86.89%
Trying model with 40 estimators ...
Model accuracy test on  test set: 81.97%
Trying model with 50 estimators ...
Model accuracy test on  test set: 83.61%
Trying model with 60 estimators ...
Model accuracy test on  test set: 86.89%
Trying model with 70 estimators ...
Model accuracy test on  test set: 81.97%
Trying model with 80 estimators ...
Model accuracy test on  test set: 83.61%
Trying model with 90 estimators ...
Model accuracy test on  test set: 86.89%

In [15]:
# 6, save a model and load it 
import pickle

pickle.dump(clf,open("random_forest_model_1.pkl","wb")) #wb stands for write binary

In [16]:
loaded_model =pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(x_test,y_test)

0.8688524590163934

## 1. Getting our data ready to be used with machine learning
Three main things we have to do:
    1. Split the data into features and labels (Usually `x` and `y`)
    2. fill missing data (also called imputing) or disregarding missing values
    3. converting non-numerical values to numerical values (also called feature encoding)

In [17]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [22]:
x = heart_disease.drop("target",axis=1)
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [23]:
y= heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [31]:
# split the data to training and test data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [33]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [34]:
x.shape

(303, 13)

In [35]:
len(heart_disease)

303

In [36]:
# so 80 % of 303 will be for training data and the remaining 20% for the test
x.shape[0]* 0.8

242.4

In [38]:
x.shape[0]* 0.2

60.6

In [39]:
242.4+60.6

303.0