In [1]:
import numpy as np

### DataTypes and Attributes

In [2]:
# Numpy's main data type is ndarray = n dimensional array

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# to know the numpy datatype
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3= np.array([ [[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]] ])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a2.dtype

dtype('int64')

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a2.ndim, a3.ndim

(2, 3)

In [9]:
a1.shape

(3,)

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
#accessing from the ndarray
a3[1][1][2]

np.int64(15)

In [12]:
# how many elements do we have
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
a2.shape

(2, 3)

### Create dataframe from numpy array

In [14]:
# pandas is build on top of pd so, we can easily use with the data frames
import pandas as pd
df = pd.DataFrame(a2)
df

   0  1  2
0  1  2  3
1  4  5  6

 # Creating arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones  = np.ones((2,3,3), dtype=int)
ones

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[0, 0, 4, 4, 8],
       [9, 1, 8, 7, 9],
       [0, 4, 0, 4, 6]], dtype=int32)

In [21]:
random_array.size, random_array.shape

(15, (3, 5))

In [22]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.76305621, 0.46417233, 0.06066572],
       [0.17011253, 0.28641526, 0.50744451],
       [0.52149206, 0.51112431, 0.68064226],
       [0.21662929, 0.21828809, 0.02179392],
       [0.82408769, 0.74178137, 0.31447051]])

In [23]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.79054245, 0.01601801, 0.2353031 ],
       [0.5481864 , 0.70170221, 0.89221229],
       [0.1409562 , 0.73560588, 0.54039339],
       [0.39304447, 0.08582869, 0.44899769],
       [0.9532531 , 0.13666823, 0.61947153]])

In [24]:
#pseduo random number - to get same random numbers again when we generate every single time.
np.random.seed(7)
random_arr_4 = np.random.random((5,3))
random_arr_4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [25]:
np.random.seed(5)
random_arr_5 = np.random.randint(10, size=(5,3))
random_arr_5

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0],
       [0, 7, 1],
       [5, 7, 0]], dtype=int32)

In [26]:
np.unique(random_arr_5)

array([0, 1, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [27]:
a1

array([1, 2, 3])

In [28]:
a1[0]

np.int64(1)

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a3[1][1][1]

np.int64(14)

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a3.shape

(2, 3, 3)

In [33]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [34]:
# when we count it it always start last one is the column for each in this case 5, then 4  is the number of rows for each or simply numpy read 
# from the outer most array, in the outer most array they are two elements then , three then the last two row and column for each respectively.

a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[1, 4, 6, 2, 9],
         [9, 9, 9, 1, 2],
         [7, 0, 5, 0, 0],
         [4, 4, 9, 3, 2]],

        [[4, 6, 9, 3, 3],
         [2, 1, 5, 7, 4],
         [3, 1, 7, 3, 1],
         [9, 5, 7, 0, 9]],

        [[6, 0, 5, 2, 8],
         [6, 8, 0, 5, 2],
         [0, 7, 7, 6, 0],
         [0, 8, 5, 5, 9]]],


       [[[6, 4, 5, 2, 8],
         [8, 1, 6, 3, 4],
         [1, 8, 0, 2, 2],
         [4, 1, 6, 3, 4]],

        [[3, 1, 4, 2, 3],
         [4, 9, 4, 0, 6],
         [6, 9, 2, 9, 3],
         [0, 8, 8, 9, 7]],

        [[4, 8, 6, 8, 0],
         [5, 3, 4, 0, 2],
         [2, 1, 1, 7, 1],
         [7, 2, 6, 3, 6]]]], dtype=int32)

In [35]:
a4.shape

(2, 3, 4, 5)

In [36]:
a4.T.shape

(5, 4, 3, 2)

In [37]:
a4.T

array([[[[1, 6],
         [4, 3],
         [6, 4]],

        [[9, 8],
         [2, 4],
         [6, 5]],

        [[7, 1],
         [3, 6],
         [0, 2]],

        [[4, 4],
         [9, 0],
         [0, 7]]],


       [[[4, 4],
         [6, 1],
         [0, 8]],

        [[9, 1],
         [1, 9],
         [8, 3]],

        [[0, 8],
         [1, 9],
         [7, 1]],

        [[4, 1],
         [5, 8],
         [8, 2]]],


       [[[6, 5],
         [9, 4],
         [5, 6]],

        [[9, 6],
         [5, 4],
         [0, 4]],

        [[5, 0],
         [7, 2],
         [7, 1]],

        [[9, 6],
         [7, 8],
         [5, 6]]],


       [[[2, 2],
         [3, 2],
         [2, 8]],

        [[1, 3],
         [7, 0],
         [5, 0]],

        [[0, 2],
         [3, 9],
         [6, 7]],

        [[3, 3],
         [0, 9],
         [5, 3]]],


       [[[9, 8],
         [3, 3],
         [8, 0]],

        [[2, 4],
         [4, 6],
         [2, 2]],

        [[0, 2],
         [1, 3],
         [0, 1]],

        [[2, 4],
         [9, 7],
         [9, 6]]]], dtype=int32)

In [38]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [39]:
a4[:1,:1,:2,:2]

array([[[[1, 4],
         [9, 9]]]], dtype=int32)

In [40]:
a4[:1,:3,:4,:5]

array([[[[1, 4, 6, 2, 9],
         [9, 9, 9, 1, 2],
         [7, 0, 5, 0, 0],
         [4, 4, 9, 3, 2]],

        [[4, 6, 9, 3, 3],
         [2, 1, 5, 7, 4],
         [3, 1, 7, 3, 1],
         [9, 5, 7, 0, 9]],

        [[6, 0, 5, 2, 8],
         [6, 8, 0, 5, 2],
         [0, 7, 7, 6, 0],
         [0, 8, 5, 5, 9]]]], dtype=int32)

In [41]:
a4[:1,:3,:3,:4]

array([[[[1, 4, 6, 2],
         [9, 9, 9, 1],
         [7, 0, 5, 0]],

        [[4, 6, 9, 3],
         [2, 1, 5, 7],
         [3, 1, 7, 3]],

        [[6, 0, 5, 2],
         [6, 8, 0, 5],
         [0, 7, 7, 6]]]], dtype=int32)

# Manipulating and Comparing arrays

## Arithmetic

In [42]:
a1

array([1, 2, 3])

In [43]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [44]:
a1 + ones

array([2., 3., 4.])

In [45]:
a1 - ones

array([0., 1., 2.])

In [46]:
a1 * ones

array([1., 2., 3.])

In [47]:
a1/ones

array([1., 2., 3.])

In [48]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [52]:
# becuse it must be reshaped to match and able to do the work here. so upto we go there letus try other arthimetics

In [53]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [54]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [55]:
np.add(a1,a2)

array([[2, 4, 6],
       [5, 7, 9]])

In [56]:
a1

array([1, 2, 3])

In [57]:
a1 % 2

array([1, 0, 1])

In [58]:
np.mod(a1,2)

array([1, 0, 1])

In [59]:
a1

array([1, 2, 3])

In [60]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [61]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

### aggregation = performing the same operation on a number of things

In [62]:
listy_list  = [1,2,3]

In [63]:
sum(listy_list)

6

In [64]:
np.sum(listy_list)

np.int64(6)

In [65]:
sum(a1)

np.int64(6)

In [66]:
np.sum(a1)

np.int64(6)

#### use python's methods (`sum()`) on python datatypes and use numpy's method on numpy arrays (`np.sum()`).

In [67]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [68]:
massive_array[:10]

array([0.14261648, 0.759887  , 0.93354342, 0.71597823, 0.12805138,
       0.122318  , 0.60531038, 0.98359658, 0.90447715, 0.26103618])

In [69]:
%timeit sum(massive_array) #python sum
%timeit np.sum(massive_array) #NumPy's sum

20.6 ms ± 2.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
117 μs ± 6.99 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [70]:
np.mean(a2)

np.float64(3.5)

In [71]:
# standard devaition is measure of how spread out a group of numbers is from the mean
np.std(a2)

np.float64(1.707825127659933)

In [72]:
#variance = measure of average degree which to each numbers is different to the mean
#higher variance = wider range of numbers
#lower variance = lower range of numbers
np.var(a2)

np.float64(2.9166666666666665)

In [73]:
np.sqrt(np.var(a2))

np.float64(1.707825127659933)

## Reshape and Transpose

In [74]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [77]:
a2.shape , a3.shape

((2, 3), (2, 3, 3))

In [78]:
# when operating arrays numpy checks their shapes, two dimensions are compatible when 
# (in the brodcasting rule) the two aray must be equal or one may be 1, so let us reshape it.
a2_reshape = a2.reshape(2,3,1)
a2_reshape, a2_reshape.shape

(array([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]]),
 (2, 3, 1))

In [79]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [80]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [81]:
# Transpose = to change the axis
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [84]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot Product

In [85]:

np.random.seed(0)
mat_1= np.random.randint(10,size = (5,3))
mat_2= np.random.randint(10,size = (5,3))

In [86]:
mat_1.shape,mat_2.shape

((5, 3), (5, 3))

In [87]:
mat_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [88]:
mat_2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [89]:
## Elemenet Wise Multiplication AKA - Hadamard product - which direct element by element multiplication
mat_1 * mat_2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [90]:
# now let us try the dot product
np.dot(mat_1,mat_2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [91]:
mat_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [92]:
# the above error is because of the shape dismatch of the arrays which affects the rule of dot products,
# so let us fix them out
# here is where the transpos comes to reshape the array so let us transpose shape of mat_2
mat_2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]], dtype=int32)

In [93]:
mat_3 =  np.dot (mat_1,mat_2.T)
mat_3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [94]:
# because of (5,3) (3,5) = (5,5) as is shows it is taking the outer as shape, to do dot product the internal must be same.
mat_3.shape

(5, 5)

## Dot product example (nut butter sales)

In [95]:
np.random.seed(0)
#num of jars sold
sales_amount = np.random.randint(20, size = (5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [96]:
weekly_sales = pd.DataFrame(sales_amount,index=["Mon","Tues","Wed","Thurs","Fri"], columns=["Almonde butter","Peanut butter", "Cashew butter"] )
weekly_sales

       Almonde butter  Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thurs               4              6             12
Fri                 1              6              7

In [97]:
weekly_sales.shape

(5, 3)

In [98]:
# create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [99]:
# create data frame for it
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Prices"],columns=["Almonde butter","Peanut butter", "Cashew butter"] )

In [100]:
butter_prices

        Almonde butter  Peanut butter  Cashew butter
Prices              10              8             12

In [101]:
butter_prices.shape

(1, 3)

In [102]:
weekly_sales.T.shape

(3, 5)

In [103]:
weekly_sales.T

                Mon  Tues  Wed  Thurs  Fri
Almonde butter   12     3    9      4    1
Peanut butter    15     3   19      6    6
Cashew butter     0     7   18     12    7

In [104]:
butter_prices

        Almonde butter  Peanut butter  Cashew butter
Prices              10              8             12

In [105]:
butter_prices.shape

(1, 3)

In [106]:
weekly_sales.shape

(5, 3)

In [107]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

        Mon  Tues  Wed  Thurs  Fri
Prices  240   138  458    232  142

In [108]:
daily_sales.shape

(1, 5)

In [109]:
weekly_sales

       Almonde butter  Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thurs               4              6             12
Fri                 1              6              7

In [110]:
weekly_sales["Total ($)"] = daily_sales.T # transpose to much the shape

In [111]:
weekly_sales

       Almonde butter  Peanut butter  Cashew butter  Total ($)
Mon                12             15              0        240
Tues                3              3              7        138
Wed                 9             19             18        458
Thurs               4              6             12        232
Fri                 1              6              7        142

## Comparison Operators

In [112]:
a1

array([1, 2, 3])

In [113]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [115]:
bool_arr = a1 >= a2
bool_arr

array([[ True,  True,  True],
       [False, False, False]])

In [116]:
type(bool_arr) , bool_arr.dtype

(numpy.ndarray, dtype('bool'))

In [117]:
a1<2

array([ True, False, False])

In [118]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting arrays

In [119]:
random_array

array([[0, 0, 4, 4, 8],
       [9, 1, 8, 7, 9],
       [0, 4, 0, 4, 6]], dtype=int32)

In [120]:
np.sort(random_array)

array([[0, 0, 4, 4, 8],
       [1, 7, 8, 9, 9],
       [0, 0, 4, 4, 6]], dtype=int32)

In [121]:
## arg plays with the indices in ndarray
np.argsort(random_array)

array([[0, 1, 2, 3, 4],
       [1, 3, 2, 0, 4],
       [0, 2, 1, 3, 4]])

In [122]:
np.argsort(a1)

array([0, 1, 2])

In [123]:
np.argmax(random_array , axis = 0)

array([1, 2, 1, 1, 1])

In [124]:
np.argmin(random_array)

np.int64(0)

In [125]:
np.argmax(random_array)

np.int64(5)

## Practical Exapmle - NumPy in action

<img src="../images/panda.png"/>

In [128]:
# turn an image to numpy array

from matplotlib.image import imread
panda = imread("../images/panda.png")
panda[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]],
      shape=(1, 3500, 3), dtype=float32)

In [129]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="../images/car-photo.png"/>

In [131]:
car = imread("../images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.48235294, 0.3529412 , 1.        ],
        [0.4509804 , 0.49019608, 0.38039216, 1.        ]],

       ...,

       [[0.47058824, 0.57254905, 0.6313726 , 1.        ],
        [0.4392157 , 0.53333336, 0.5882353 , 1.        ],
        [0.48235294, 0.5803922 , 0.6392157 , 1.        ],
        ...,
        [0.6156863 , 0.7529412 , 0.827451  , 1.        ],
        [0.61960787, 0.7607843 , 0.83137256, 1.        ],
        [0.5921569 , 0.73333335, 0.7921569 , 1.        ]],

       [[0.4745098 , 0.5803922 , 0.6392157 , 1.        ],
        [0.47058824, 0.58431375, 0.63529414, 1.        ],
        [0.4117647 , 0.5019608 , 0.5529412 , 1.        ],
        ...,
        [0.54901963, 0.6784314 , 0.74509805, 1.        ],
        [0.65882355, 0.8117647 , 0.8862745 , 1.        ],
        [0.60784316, 0.74509805, 0.8117647 , 1.        ]],

       [[0.4745098 , 0.57254905, 0.627451  , 1.        ],
        [0.49411765, 0.6       , 0.65882355, 1.        ],
        [0.49019608, 0.5921569 , 0.64705884, 1.        ],
        ...,
        [0.5294118 , 0.63529414, 0.69803923, 1.        ],
        [0.5529412 , 0.67058825, 0.7372549 , 1.        ],
        [0.6156863 , 0.73333335, 0.8       , 1.        ]]],
      shape=(431, 575, 4), dtype=float32)

In [132]:
car.dtype

dtype('float32')

In [133]:
car.size , car.shape

(991300, (431, 575, 4))

<img src="../images/dog-photo.png"/>

In [134]:
dog = imread("../images/dog-photo.png")
dog[1]

array([[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
       [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
       [0.7058824 , 0.80784315, 0.88235295, 1.        ],
       ...,
       [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
       [0.49411765, 0.68235296, 0.84313726, 1.        ],
       [0.49411765, 0.68235296, 0.8392157 , 1.        ]],
      shape=(575, 4), dtype=float32)

In [135]:
## so like the above manipulation we can work with different algorithms and model based on
## this number values. BYE BYE